/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  closed_at: Timestamp | null;
  external_account_number: string | null;
  id: Generated<Int8>;
  institution: string;
  kind: string;
  name: string;
  owner_id: Int8;
  tax_treatment: string;
}

export interface Classification {
  asset_class: string;
  id: Generated<Int8>;
  name: string;
}

export interface ColumnMapping {
  header_fingerprint: string;
  id: Generated<Int8>;
  institution: string;
  mapping: Json;
}

export interface Holding {
  cost_basis_per_share: Numeric | null;
  id: Generated<Int8>;
  instrument_id: Int8;
  position_set_id: Int8;
  quantity: Numeric;
}

export interface HoldingValued {
  account_id: Int8 | null;
  account_kind: string | null;
  account_name: string | null;
  asset_class: string | null;
  classification: string | null;
  cost_basis: Numeric | null;
  cost_basis_per_share: Numeric | null;
  institution: string | null;
  instrument_id: Int8 | null;
  instrument_name: string | null;
  is_priced: boolean | null;
  is_stale: boolean | null;
  owner_id: Int8 | null;
  owner_name: string | null;
  price: Numeric | null;
  price_source: string | null;
  quantity: Numeric | null;
  quote_type: string | null;
  symbol: string | null;
  tax_treatment: string | null;
  unrealized: Numeric | null;
  value: Numeric | null;
}

export interface Instrument {
  classification_id: Int8;
  id: Generated<Int8>;
  name: string;
  price_source: string;
  quote_type: string | null;
  symbol: string | null;
}

export interface InstrumentAlias {
  instrument_id: Int8;
  raw_string: string;
}

export interface ManualNetworth {
  amount: Numeric;
  date: string;
}

export interface Person {
  id: Generated<Int8>;
  name: string;
}

export interface PositionSet {
  account_id: Int8;
  as_of_date: string;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  raw_file: Buffer | null;
  source: string;
  source_filename: string | null;
}

export interface PriceDaily {
  close: Numeric;
  date: string;
  instrument_id: Int8;
}

export interface Quote {
  annual_dividend_per_share: Numeric | null;
  as_of: Timestamp;
  instrument_id: Int8;
  is_stale: Generated<boolean>;
  price: Numeric;
  yield_pct: Numeric | null;
}

export interface SchemaMigrations {
  applied_at: Generated<Timestamp>;
  filename: string;
}

export interface UploadDraft {
  account_id: Int8;
  as_of_date: string | null;
  created_at: Generated<Timestamp>;
  filename: string;
  had_first_sightings: boolean | null;
  id: Generated<Int8>;
  mapping: Json | null;
  raw_file: Buffer;
}

export interface DB {
  account: Account;
  classification: Classification;
  column_mapping: ColumnMapping;
  holding: Holding;
  holding_valued: HoldingValued;
  instrument: Instrument;
  instrument_alias: InstrumentAlias;
  manual_networth: ManualNetworth;
  person: Person;
  position_set: PositionSet;
  price_daily: PriceDaily;
  quote: Quote;
  schema_migrations: SchemaMigrations;
  upload_draft: UploadDraft;
}
