import { fileURLToPath } from "node:url";

import { defineConfig } from "vitest/config";

// No React Router Vite plugin: its route/manifest generation only gets in the way.
export default defineConfig({
  resolve: {
    // In step with `vite.config.ts` — see there for why this is written out.
    alias: [
      { find: /^~\//, replacement: fileURLToPath(new URL("./app/", import.meta.url)) },
    ],
  },
  test: {
    environment: "node",
    // A loader calls `getConfig()`, which refuses without a `DATABASE_URL`.
    // Tests never connect through it — `withDatabase` puts a transaction in
    // async storage — so this points at the suite's own throwaway Postgres to
    // keep the one demanded variable truthful rather than invented.
    env: {
      DATABASE_URL:
        process.env.TEST_DATABASE_URL ??
        "postgres://portfolio:portfolio@127.0.0.1:55432/portfolio_test",
    },
    include: ["tests/**/*.test.ts", "tests/**/*.test.tsx"],
    // Integration tests share one Postgres; keep them off each other's toes.
    fileParallelism: false,
    // `npm run test:coverage`. Deliberately no CI gate, no threshold — a
    // failing percentage breeds tests written for the number, not for a rule.
    // The useful reading is which *files* are dark, not the total.
    coverage: {
      include: ["app/**", "server/**"],
      // Generated by `npm run db:types`; nothing here anyone wrote.
      exclude: ["app/lib/database.generated.ts"],
    },
  },
});
