import { fileURLToPath } from "node:url";

import { defineConfig } from "vitest/config";

// No React Router Vite plugin: its route/manifest generation only gets in the way.
export default defineConfig({
  resolve: {
    // In step with `vite.config.ts` — see there for why this is written out.
    alias: [
      { find: /^~\//, replacement: fileURLToPath(new URL("./app/", import.meta.url)) },
    ],
  },
  test: {
    environment: "node",
    // A loader calls `getConfig()`, which refuses without a `DATABASE_URL` —
    // and now without `PUBLIC_ORIGIN` too, a second required key with no
    // default, so every test reaching `getConfig()` (a route loader, a
    // domain module) fails without both. Tests never connect through
    // DATABASE_URL — `withDatabase` puts a transaction in async storage — so
    // it points at the suite's own throwaway Postgres to keep the demanded
    // variable truthful rather than invented. PUBLIC_ORIGIN agrees with the
    // suite on only the host: `tests/support/routes.ts`'s request builders
    // already address this instance as `portfolio.local`. The scheme
    // deliberately does not match — the builders address it as
    // `http://portfolio.local` and predate the lock, while this is
    // `https://` because a real WebAuthn ceremony will not run outside a
    // secure context, and `localhost` is the only exception `server/config.ts`
    // carves out for `http://`.
    env: {
      DATABASE_URL:
        process.env.TEST_DATABASE_URL ??
        "postgres://portfolio:portfolio@127.0.0.1:55432/portfolio_test",
      PUBLIC_ORIGIN: "https://portfolio.local",
    },
    include: ["tests/**/*.test.ts", "tests/**/*.test.tsx"],
    // Integration tests share one Postgres; keep them off each other's toes.
    fileParallelism: false,
    // `npm run test:coverage`. Deliberately no CI gate, no threshold — a
    // failing percentage breeds tests written for the number, not for a rule.
    // The useful reading is which *files* are dark, not the total.
    coverage: {
      include: ["app/**", "server/**"],
      // Generated by `npm run db:types`; nothing here anyone wrote.
      exclude: ["app/lib/database.generated.ts"],
    },
  },
});
